// Generated by tools/gen-index.mjs — do not edit by hand.
import p_african_african_american_studies_minor from './african-african-american-studies-minor.js';
import p_ancient_mediterranean_civilization_ba from './ancient-mediterranean-civilization-ba.js';
import p_anthropology_ba from './anthropology-ba.js';
import p_anthropology_minor from './anthropology-minor.js';
import p_applied_physics_bs from './applied-physics-bs.js';
import p_architectural_studies_ba from './architectural-studies-ba.js';
import p_architecture_ba from './architecture-ba.js';
import p_architecture_barch_direct_entry from './architecture-barch-direct-entry.js';
import p_architecture_barch from './architecture-barch.js';
import p_art_ba from './art-ba.js';
import p_art_history_ba from './art-history-ba.js';
import p_art_history_minor from './art-history-minor.js';
import p_artificial_intelligence_bs from './artificial-intelligence-bs.js';
import p_asian_studies_ba_asian_language_concentration from './asian-studies-ba-asian-language-concentration.js';
import p_asian_studies_ba_transnational_asian_studies_concentration from './asian-studies-ba-transnational-asian-studies-concentration.js';
import p_asian_studies_minor from './asian-studies-minor.js';
import p_astronomy_ba from './astronomy-ba.js';
import p_astronomy_minor from './astronomy-minor.js';
import p_astrophysics_bs from './astrophysics-bs.js';
import p_behavioral_medicine_health_resilience_minor from './behavioral-medicine-health-resilience-minor.js';
import p_biochemistry_ba from './biochemistry-ba.js';
import p_biochemistry_bs from './biochemistry-bs.js';
import p_biochemistry_cell_biology_minor from './biochemistry-cell-biology-minor.js';
import p_bioengineering_bsbe from './bioengineering-bsbe.js';
import p_biological_physics_bs from './biological-physics-bs.js';
import p_business_finance_ba from './business-finance-ba.js';
import p_business_management_ba from './business-management-ba.js';
import p_business_marketing_ba from './business-marketing-ba.js';
import p_business_minor from './business-minor.js';
import p_cell_biology_and_genetics_ba from './cell-biology-and-genetics-ba.js';
import p_cell_biology_and_genetics_bs from './cell-biology-and-genetics-bs.js';
import p_chemical_engineering_ba from './chemical-engineering-ba.js';
import p_chemical_physics_bs from './chemical-physics-bs.js';
import p_chemistry_ba from './chemistry-ba.js';
import p_chemistry_bs from './chemistry-bs.js';
import p_cinema_media_studies_minor from './cinema-media-studies-minor.js';
import p_civil_engineering_bsce from './civil-engineering-bsce.js';
import p_civil_environmental_engineering_ba_civil_concentration from './civil-environmental-engineering-ba-civil-concentration.js';
import p_civil_environmental_engineering_ba_environmental_concentration from './civil-environmental-engineering-ba-environmental-concentration.js';
import p_classical_civilizations_minor from './classical-civilizations-minor.js';
import p_classical_studies_ba from './classical-studies-ba.js';
import p_cognitive_sciences_ba from './cognitive-sciences-ba.js';
import p_composition_bmus from './composition-bmus.js';
import p_computational_applied_mathematics_ba from './computational-applied-mathematics-ba.js';
import p_computational_applied_mathematics_minor from './computational-applied-mathematics-minor.js';
import p_computational_neuroscience_bs from './computational-neuroscience-bs.js';
import p_computational_physics_bs from './computational-physics-bs.js';
import p_computer_science_ba from './computer-science-ba.js';
import p_computer_science_bscs from './computer-science-bscs.js';
import p_creative_writing_minor from './creative-writing-minor.js';
import p_data_science_minor from './data-science-minor.js';
import p_digital_health_minor from './digital-health-minor.js';
import p_earth_environmental_planetary_sciences_minor from './earth-environmental-planetary-sciences-minor.js';
import p_ecology_and_evolutionary_biology_ba from './ecology-and-evolutionary-biology-ba.js';
import p_ecology_and_evolutionary_biology_bs from './ecology-and-evolutionary-biology-bs.js';
import p_ecology_evolutionary_biology_minor from './ecology-evolutionary-biology-minor.js';
import p_economics_ba from './economics-ba.js';
import p_electrical_computer_engineering_ba from './electrical-computer-engineering-ba.js';
import p_electrical_computer_engineering_bsece from './electrical-computer-engineering-bsece.js';
import p_energy_water_sustainability_minor from './energy-water-sustainability-minor.js';
import p_english_ba_creative_writing_concentration from './english-ba-creative-writing-concentration.js';
import p_english_ba from './english-ba.js';
import p_english_minor from './english-minor.js';
import p_entrepreneurship_minor from './entrepreneurship-minor.js';
import p_environmental_engineering_bsenve from './environmental-engineering-bsenve.js';
import p_environmental_science_ba_earth_concentration from './environmental-science-ba-earth-concentration.js';
import p_environmental_science_ba_ecology_evolutionary_biology_concentration from './environmental-science-ba-ecology-evolutionary-biology-concentration.js';
import p_environmental_science_bs_earth_science_concentration from './environmental-science-bs-earth-science-concentration.js';
import p_environmental_science_bs_ecology_evolutionary_biology_concentration from './environmental-science-bs-ecology-evolutionary-biology-concentration.js';
import p_environmental_studies_minor from './environmental-studies-minor.js';
import p_european_studies_ba from './european-studies-ba.js';
import p_financial_computation_modeling_minor from './financial-computation-modeling-minor.js';
import p_french_studies_ba from './french-studies-ba.js';
import p_french_studies_minor from './french-studies-minor.js';
import p_general_physics_bs from './general-physics-bs.js';
import p_german_studies_ba from './german-studies-ba.js';
import p_german_studies_minor from './german-studies-minor.js';
import p_global_affairs_ba from './global-affairs-ba.js';
import p_global_health_technologies_minor from './global-health-technologies-minor.js';
import p_greek_minor from './greek-minor.js';
import p_history_ba_international_studies_concentration from './history-ba-international-studies-concentration.js';
import p_history_ba from './history-ba.js';
import p_integrative_biology_ba from './integrative-biology-ba.js';
import p_integrative_biology_bs from './integrative-biology-bs.js';
import p_jewish_studies_minor from './jewish-studies-minor.js';
import p_latin_american_latinx_studies_ba from './latin-american-latinx-studies-ba.js';
import p_latin_american_latinx_studies_minor from './latin-american-latinx-studies-minor.js';
import p_latin_minor from './latin-minor.js';
import p_linguistics_ba from './linguistics-ba.js';
import p_managerial_economics_organizational_sciences_ba from './managerial-economics-organizational-sciences-ba.js';
import p_materials_science_nanoengineering_ba from './materials-science-nanoengineering-ba.js';
import p_materials_science_nanoengineering_bsmsne from './materials-science-nanoengineering-bsmsne.js';
import p_mathematical_economic_analysis_ba from './mathematical-economic-analysis-ba.js';
import p_mathematics_ba from './mathematics-ba.js';
import p_mathematics_bs from './mathematics-bs.js';
import p_mathematics_minor from './mathematics-minor.js';
import p_mechanical_engineering_ba from './mechanical-engineering-ba.js';
import p_mechanical_engineering_bsme from './mechanical-engineering-bsme.js';
import p_media_studies_ba from './media-studies-ba.js';
import p_medical_humanities_minor from './medical-humanities-minor.js';
import p_medieval_early_modern_studies_ba from './medieval-early-modern-studies-ba.js';
import p_molecular_cellular_neuroscience_bs from './molecular-cellular-neuroscience-bs.js';
import p_museums_cultural_heritage_minor from './museums-cultural-heritage-minor.js';
import p_music_ba from './music-ba.js';
import p_music_history_bmus from './music-history-bmus.js';
import p_music_theory_bmus from './music-theory-bmus.js';
import p_naval_science_minor from './naval-science-minor.js';
import p_neuroscience_ba from './neuroscience-ba.js';
import p_neuroscience_minor from './neuroscience-minor.js';
import p_operations_research_ba from './operations-research-ba.js';
import p_operations_research_bs from './operations-research-bs.js';
import p_operations_research_minor from './operations-research-minor.js';
import p_philosophy_ba from './philosophy-ba.js';
import p_philosophy_minor from './philosophy-minor.js';
import p_physics_ba from './physics-ba.js';
import p_physics_minor from './physics-minor.js';
import p_political_science_ba from './political-science-ba.js';
import p_politics_law_social_thought_minor from './politics-law-social-thought-minor.js';
import p_psychology_ba from './psychology-ba.js';
import p_public_health_sciences_ba from './public-health-sciences-ba.js';
import p_religion_ba from './religion-ba.js';
import p_religion_minor from './religion-minor.js';
import p_science_technology_studies_minor from './science-technology-studies-minor.js';
import p_sociology_ba from './sociology-ba.js';
import p_sociology_minor from './sociology-minor.js';
import p_spanish_and_portuguese_ba from './spanish-and-portuguese-ba.js';
import p_spanish_and_portuguese_minor from './spanish-and-portuguese-minor.js';
import p_sport_analytics_ba from './sport-analytics-ba.js';
import p_sport_management_ba_law_concentration from './sport-management-ba-law-concentration.js';
import p_sport_management_ba_leadership_concentration from './sport-management-ba-leadership-concentration.js';
import p_sports_medicine_exercise_physiology_ba from './sports-medicine-exercise-physiology-ba.js';
import p_sports_medicine_exercise_physiology_bs from './sports-medicine-exercise-physiology-bs.js';
import p_statistics_ba from './statistics-ba.js';
import p_statistics_bs from './statistics-bs.js';
import p_statistics_minor from './statistics-minor.js';
import p_theatre_minor from './theatre-minor.js';
import p_women_gender_sexuality_ba from './women-gender-sexuality-ba.js';
import p_women_gender_sexuality_minor from './women-gender-sexuality-minor.js';

export default [
  p_african_african_american_studies_minor,
  p_ancient_mediterranean_civilization_ba,
  p_anthropology_ba,
  p_anthropology_minor,
  p_applied_physics_bs,
  p_architectural_studies_ba,
  p_architecture_ba,
  p_architecture_barch_direct_entry,
  p_architecture_barch,
  p_art_ba,
  p_art_history_ba,
  p_art_history_minor,
  p_artificial_intelligence_bs,
  p_asian_studies_ba_asian_language_concentration,
  p_asian_studies_ba_transnational_asian_studies_concentration,
  p_asian_studies_minor,
  p_astronomy_ba,
  p_astronomy_minor,
  p_astrophysics_bs,
  p_behavioral_medicine_health_resilience_minor,
  p_biochemistry_ba,
  p_biochemistry_bs,
  p_biochemistry_cell_biology_minor,
  p_bioengineering_bsbe,
  p_biological_physics_bs,
  p_business_finance_ba,
  p_business_management_ba,
  p_business_marketing_ba,
  p_business_minor,
  p_cell_biology_and_genetics_ba,
  p_cell_biology_and_genetics_bs,
  p_chemical_engineering_ba,
  p_chemical_physics_bs,
  p_chemistry_ba,
  p_chemistry_bs,
  p_cinema_media_studies_minor,
  p_civil_engineering_bsce,
  p_civil_environmental_engineering_ba_civil_concentration,
  p_civil_environmental_engineering_ba_environmental_concentration,
  p_classical_civilizations_minor,
  p_classical_studies_ba,
  p_cognitive_sciences_ba,
  p_composition_bmus,
  p_computational_applied_mathematics_ba,
  p_computational_applied_mathematics_minor,
  p_computational_neuroscience_bs,
  p_computational_physics_bs,
  p_computer_science_ba,
  p_computer_science_bscs,
  p_creative_writing_minor,
  p_data_science_minor,
  p_digital_health_minor,
  p_earth_environmental_planetary_sciences_minor,
  p_ecology_and_evolutionary_biology_ba,
  p_ecology_and_evolutionary_biology_bs,
  p_ecology_evolutionary_biology_minor,
  p_economics_ba,
  p_electrical_computer_engineering_ba,
  p_electrical_computer_engineering_bsece,
  p_energy_water_sustainability_minor,
  p_english_ba_creative_writing_concentration,
  p_english_ba,
  p_english_minor,
  p_entrepreneurship_minor,
  p_environmental_engineering_bsenve,
  p_environmental_science_ba_earth_concentration,
  p_environmental_science_ba_ecology_evolutionary_biology_concentration,
  p_environmental_science_bs_earth_science_concentration,
  p_environmental_science_bs_ecology_evolutionary_biology_concentration,
  p_environmental_studies_minor,
  p_european_studies_ba,
  p_financial_computation_modeling_minor,
  p_french_studies_ba,
  p_french_studies_minor,
  p_general_physics_bs,
  p_german_studies_ba,
  p_german_studies_minor,
  p_global_affairs_ba,
  p_global_health_technologies_minor,
  p_greek_minor,
  p_history_ba_international_studies_concentration,
  p_history_ba,
  p_integrative_biology_ba,
  p_integrative_biology_bs,
  p_jewish_studies_minor,
  p_latin_american_latinx_studies_ba,
  p_latin_american_latinx_studies_minor,
  p_latin_minor,
  p_linguistics_ba,
  p_managerial_economics_organizational_sciences_ba,
  p_materials_science_nanoengineering_ba,
  p_materials_science_nanoengineering_bsmsne,
  p_mathematical_economic_analysis_ba,
  p_mathematics_ba,
  p_mathematics_bs,
  p_mathematics_minor,
  p_mechanical_engineering_ba,
  p_mechanical_engineering_bsme,
  p_media_studies_ba,
  p_medical_humanities_minor,
  p_medieval_early_modern_studies_ba,
  p_molecular_cellular_neuroscience_bs,
  p_museums_cultural_heritage_minor,
  p_music_ba,
  p_music_history_bmus,
  p_music_theory_bmus,
  p_naval_science_minor,
  p_neuroscience_ba,
  p_neuroscience_minor,
  p_operations_research_ba,
  p_operations_research_bs,
  p_operations_research_minor,
  p_philosophy_ba,
  p_philosophy_minor,
  p_physics_ba,
  p_physics_minor,
  p_political_science_ba,
  p_politics_law_social_thought_minor,
  p_psychology_ba,
  p_public_health_sciences_ba,
  p_religion_ba,
  p_religion_minor,
  p_science_technology_studies_minor,
  p_sociology_ba,
  p_sociology_minor,
  p_spanish_and_portuguese_ba,
  p_spanish_and_portuguese_minor,
  p_sport_analytics_ba,
  p_sport_management_ba_law_concentration,
  p_sport_management_ba_leadership_concentration,
  p_sports_medicine_exercise_physiology_ba,
  p_sports_medicine_exercise_physiology_bs,
  p_statistics_ba,
  p_statistics_bs,
  p_statistics_minor,
  p_theatre_minor,
  p_women_gender_sexuality_ba,
  p_women_gender_sexuality_minor,
];
