#!/usr/bin/env python3
"""Builds data/rice/courses/<DEPT>.json from descriptions.json (catalog details) and the schedule crawl.

Usage: python3 tools/gen-course-data.py descriptions.json [sched_dir] [terms...]
Each dept file maps course code -> { t: title, d: description, dist, pre, level, x: crosslist, o: [term codes offered] }.
Also writes js/schools/rice/schedule.js with the list of crawled term codes.
"""
import glob, html, json, os, re, sys
from collections import defaultdict

desc = json.load(open(sys.argv[1]))
# Optional: ad.json beside descriptions.json lists Analyzing Diversity courses.
_ad_path = os.path.join(os.path.dirname(sys.argv[1]), 'ad.json')
AD = set(json.load(open(_ad_path))) if os.path.exists(_ad_path) else set()
sched_dir = sys.argv[2] if len(sys.argv) > 2 else None
terms = sys.argv[3:]
offered = defaultdict(set)
if sched_dir:
    for f in glob.glob(os.path.join(sched_dir, '*.html')):
        parts = os.path.basename(f)[:-5].split('_')
        term = next((x for x in parts if re.fullmatch(r'\d{6}', x)), None)
        if not term: continue
        s = open(f, errors='ignore').read()
        for cell in re.findall(r'class="cls-crs"[^>]*>(.*?)</td>', s, re.S):
            t = re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', '', cell))).strip()
            m = re.match(r'([A-Z]{2,5}) (\d{3}[A-Z]?) ', t + ' ')
            if m: offered[f'{m.group(1)} {m.group(2)}'].add(term)
        if term not in terms: terms.append(term)
terms = sorted(set(terms))
by_dept = defaultdict(dict)
for code in set(desc) | set(offered):
    rec = dict(desc.get(code, {}))
    if code in offered: rec['o'] = sorted(offered[code])
    if code in AD: rec['ad'] = 1
    by_dept[code.split(' ')[0]][code] = rec
os.makedirs('data/rice/courses', exist_ok=True)
for dept, m in by_dept.items():
    json.dump(m, open(f'data/rice/courses/{dept}.json', 'w'), separators=(',', ':'))
# Small attribute index so distribution and diversity suggestions need one request, not one per department.
attrs = {'dist': defaultdict(list), 'ad': sorted(AD)}
for code, rec in desc.items():
    g = (rec.get('dist') or '').replace('Distribution Group ', '')
    if g: attrs['dist'][g].append(code)
json.dump({'dist': {g: sorted(v) for g, v in attrs['dist'].items()}, 'ad': attrs['ad']}, open('data/rice/attributes.json', 'w'), separators=(',', ':'))
with open('js/schools/rice/schedule.js', 'w') as f:
    f.write('// Generated by tools/gen-course-data.py: term codes covered by the offering data (YYYY10=Fall of YYYY-1, 20=Spring, 30=Summer).\n')
    f.write('export default ' + json.dumps(terms) + ';\n')
print(f'{len(by_dept)} department files, {sum(len(m) for m in by_dept.values())} courses, {len(offered)} with offerings, {len(terms)} terms')
