// Builds js/schools/rice/catalog.js from a JSON map { "COMP 140": ["COMPUTATIONAL THINKING", 4], ... }
// Usage: node tools/gen-catalog.mjs path/to/catalog.json
import { readFileSync, writeFileSync } from 'node:fs';
const map = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const title = (t) => t.replace(/\s+/g, ' ').trim();
const body = Object.keys(map).sort().map((k) => `${JSON.stringify(k)}:[${JSON.stringify(title(map[k][0]))},${map[k][1]}]`).join(',\n');
writeFileSync('js/schools/rice/catalog.js', `// Generated by tools/gen-catalog.mjs from the Rice General Announcements course listings.\n// code -> { title, hours }\nconst raw = {\n${body}\n};\nconst catalog = {};\nfor (const k in raw) catalog[k] = { title: raw[k][0], hours: raw[k][1] };\nexport default catalog;\n`);
console.log(`wrote catalog with ${Object.keys(map).length} courses`);
