// Regenerates, from the files in js/schools/<school>/programs/:
//   programs/index.js      one import per program (used by the validator and for authoring)
//   programs.bundle.js     every program inlined in one module, so the browser makes 1 request instead of ~140
// Usage: node tools/gen-index.mjs [rice]
import { readdirSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';

const school = process.argv[2] || 'rice';
const dir = `js/schools/${school}/programs`;
const files = readdirSync(dir).filter((f) => f.endsWith('.js') && f !== 'index.js').sort();
const ident = (f) => 'p_' + f.replace(/\.js$/, '').replace(/[^a-z0-9]/gi, '_');
writeFileSync(`${dir}/index.js`, `// Generated by tools/gen-index.mjs — do not edit by hand.\n` +
  files.map((f) => `import ${ident(f)} from './${f}';`).join('\n') +
  `\n\nexport default [\n${files.map((f) => `  ${ident(f)},`).join('\n')}\n];\n`);

const programs = [];
for (const f of files) programs.push((await import(`${pathToFileURL(resolve(dir, f)).href}?t=${Date.now()}`)).default);
writeFileSync(`js/schools/${school}/programs.bundle.js`,
  `// Generated by tools/gen-index.mjs from programs/*.js — do not edit by hand. Edit the program files, then re-run.\n` +
  `export default ${JSON.stringify(programs)};\n`);
console.log(`wrote ${dir}/index.js and programs.bundle.js with ${files.length} programs`);
