#!/usr/bin/env python3
"""Builds data/rice/schedule/<term>.json (course sections with meeting times) from the schedule crawl.

Usage: python3 tools/gen-schedule.py <sched_dir> <descriptions.json> <term> [<term> ...]
Section record: [crn, code, section, title, instructor, credits, dist, partOfTerm, [[days, startMin, endMin], ...]]
Also writes js/schools/rice/section-terms.js listing the terms generated.
"""
import html, json, os, re, sys
from collections import defaultdict

sched_dir, desc_path, *terms = sys.argv[1:]
desc = json.load(open(desc_path))
clean = lambda t: re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', t))).strip()

def to_min(t):
    m = re.match(r'(\d{1,2}):(\d{2})(AM|PM)', t)
    h, mi, ap = int(m.group(1)), int(m.group(2)), m.group(3)
    if ap == 'PM' and h != 12: h += 12
    if ap == 'AM' and h == 12: h = 0
    return h * 60 + mi

os.makedirs('data/rice/schedule', exist_ok=True)
written = []
for term in terms:
    sections = []
    for f in sorted(os.listdir(sched_dir)):
        if not f.endswith(f'_{term}.html'): continue
        s = open(os.path.join(sched_dir, f), errors='ignore').read()
        for row in re.findall(r'<tr[^>]*>(.*?)</tr>', s, re.S):
            cells = dict(re.findall(r'class="(cls-[a-z]+)"[^>]*>(.*?)</td>', row, re.S))
            if 'cls-crs' not in cells: continue
            crs = clean(cells['cls-crs'])
            m = re.match(r'([A-Z]{2,5}) (\d{3}[A-Z]?) (\S+)', crs)
            if not m: continue
            code, sec = f'{m.group(1)} {m.group(2)}', m.group(3)
            meetings = []
            mtg = cells.get('cls-mtg', '')
            mtg = mtg.split('<div class="mtg-finl"')[0]
            for blk in re.findall(r'<div class="mtg-clas"[^>]*>(.*)', mtg, re.S):
                for line in re.findall(r'<div>(.*?)</div>', blk, re.S):
                    t = clean(line)
                    mm = re.match(r'(\d{1,2}:\d{2}[AP]M) - (\d{1,2}:\d{2}[AP]M) ([MTWRFSU]+)', t)
                    if mm: meetings.append([mm.group(3), to_min(mm.group(1)), to_min(mm.group(2))])
            credits = clean(cells.get('cls-crd', '')) or ''
            d = desc.get(code, {})
            dist = (d.get('dist') or '').replace('Distribution Group ', '')
            sections.append([int(clean(cells['cls-crn'])), code, sec, clean(cells.get('cls-ttl', '')), clean(cells.get('cls-ins', '')), credits, dist, clean(cells.get('cls-ses', '')), meetings])
    if not sections: continue
    json.dump({'term': term, 'sections': sections}, open(f'data/rice/schedule/{term}.json', 'w'), separators=(',', ':'))
    written.append(term)
    with_times = sum(1 for x in sections if x[8])
    print(f'{term}: {len(sections)} sections, {with_times} with meeting times')
with open('js/schools/rice/section-terms.js', 'w') as f:
    f.write('// Generated by tools/gen-schedule.py: terms with section-level schedule data in data/rice/schedule/.\n')
    f.write('export default ' + json.dumps(sorted(written)) + ';\n')
    import datetime
    f.write('export const generated = ' + json.dumps(datetime.date.today().isoformat()) + ';\n')
