// Regenerates js/schools/<school>/programs/index.js from the files in that directory.
// Usage: node tools/gen-index.mjs [rice]
import { readdirSync, writeFileSync } from 'node:fs';
const school = process.argv[2] || 'rice';
const dir = `js/schools/${school}/programs`;
const files = readdirSync(dir).filter((f) => f.endsWith('.js') && f !== 'index.js').sort();
const ident = (f) => 'p_' + f.replace(/\.js$/, '').replace(/[^a-z0-9]/gi, '_');
const src = `// Generated by tools/gen-index.mjs — do not edit by hand.\n` +
  files.map((f) => `import ${ident(f)} from './${f}';`).join('\n') +
  `\n\nexport default [\n${files.map((f) => `  ${ident(f)},`).join('\n')}\n];\n`;
writeFileSync(`${dir}/index.js`, src);
console.log(`wrote ${dir}/index.js with ${files.length} programs`);
