// Generated by tools/gen-course-data.py: term codes covered by the offering data (YYYY10=Fall of YYYY-1, 20=Spring, 30=Summer).
export default ["202310", "202320", "202330", "202410", "202420", "202430", "202510", "202520", "202530", "202610", "202620", "202630", "202710"];
